spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/knowledgehub
    username: knowledgehub
    password: knowledgehub
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-local-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-local-secret}
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.dibya.knowledgehub: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: bG9jYWwtZGV2LXNlY3JldC1taW4tMzItY2hhcnMtbG9uZy1yZXBsYWNlLWluLXByb2Q=
  cors:
    allowed-origins: http://localhost:5173
  ai:
    provider: ollama
    embedding-provider: ollama
  storage:
    location: ./uploads
